name: Deploy to EvenNode

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to EvenNode
        uses: rodnye/evennode-deploy-action@v1
        with:
          key: ${{ secrets.EVENNODE_SSH_KEY }}
          git_email: ${{ secrets.GIT_EMAIL }}
          git_name: ${{ secrets.GIT_NAME }}
          git_url: ${{ secrets.EVENNODE_GIT_URL }}
          dot_env: ${{ secrets.DOT_ENV }}