name: Deploy to EvenNode

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: evennode
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Add .env in client folder
        run: |
          echo "${{ secrets.DOT_ENV_CLIENT }}" > ./client/.env
          echo "${{ secrets.DOT_ENV_SERVER }}" > ./server/.env

      - name: Build for upload puppeteer cache (Evennode ignore them)
        run: |
          pnpm install
          pnpm build

      - name: EvenNode Deploy
        uses: rodnye/evennode-deploy-action@v1
        with:
          key: ${{ secrets.EVENNODE_SSH_KEY }}
          git_url: ${{ secrets.EVENNODE_REPO_URL }}
          git_name: ${{ secrets.GIT_NAME }}
          git_email: ${{ secrets.GIT_EMAIL }}
          pre_commit_command: |
            echo "Adding bundled folders to upload" 
            git add server/.cache server/public/dist server/.env -f
