name: Deploy to EvenNode

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: evennode
    steps:
      - uses: actions/checkout@v4
      
      - name: EvenNode Deploy
        uses: rodnye/evennode-deploy-action@v1
        with:
          key: ${{ secrets.EVENNODE_SSH_KEY }}
          git_url: ${{ secrets.EVENNODE_REPO_URL }}
          dot_env: ${{ secrets.DOT_ENV }}
          git_name: ${{ secrets.GIT_NAME }}
          git_email: ${{ secrets.GIT_EMAIL }}
          pre_commit_command: 'mv .env server && git add server/.env -f'